/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ZKFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createZKContract"
      | "getUserZkContract"
      | "implementation"
      | "userZkContract"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ZKContractCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createZKContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserZkContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userZkContract",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createZKContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserZkContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userZkContract",
    data: BytesLike
  ): Result;
}

export namespace ZKContractCreatedEvent {
  export type InputTuple = [user: AddressLike, zkContract: AddressLike];
  export type OutputTuple = [user: string, zkContract: string];
  export interface OutputObject {
    user: string;
    zkContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZKFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ZKFactory;
  waitForDeployment(): Promise<this>;

  interface: ZKFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createZKContract: TypedContractMethod<
    [_userContractAddr: AddressLike],
    [string],
    "nonpayable"
  >;

  getUserZkContract: TypedContractMethod<[user: AddressLike], [string], "view">;

  implementation: TypedContractMethod<[], [string], "view">;

  userZkContract: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createZKContract"
  ): TypedContractMethod<
    [_userContractAddr: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getUserZkContract"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userZkContract"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "ZKContractCreated"
  ): TypedContractEvent<
    ZKContractCreatedEvent.InputTuple,
    ZKContractCreatedEvent.OutputTuple,
    ZKContractCreatedEvent.OutputObject
  >;

  filters: {
    "ZKContractCreated(address,address)": TypedContractEvent<
      ZKContractCreatedEvent.InputTuple,
      ZKContractCreatedEvent.OutputTuple,
      ZKContractCreatedEvent.OutputObject
    >;
    ZKContractCreated: TypedContractEvent<
      ZKContractCreatedEvent.InputTuple,
      ZKContractCreatedEvent.OutputTuple,
      ZKContractCreatedEvent.OutputObject
    >;
  };
}
