/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDKIMRegistry,
  IDKIMRegistryInterface,
} from "../../../../@zk-email/contracts/interfaces/IDKIMRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "domainName",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "publicKeyHash",
        type: "bytes32",
      },
    ],
    name: "isDKIMPublicKeyHashValid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDKIMRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IDKIMRegistryInterface {
    return new Interface(_abi) as IDKIMRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDKIMRegistry {
    return new Contract(address, _abi, runner) as unknown as IDKIMRegistry;
  }
}
