/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface DecimalUtilsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "uintToDecimalString(uint256)"
      | "uintToDecimalString(uint256,uint256)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "uintToDecimalString(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uintToDecimalString(uint256,uint256)",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "uintToDecimalString(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uintToDecimalString(uint256,uint256)",
    data: BytesLike
  ): Result;
}

export interface DecimalUtils extends BaseContract {
  connect(runner?: ContractRunner | null): DecimalUtils;
  waitForDeployment(): Promise<this>;

  interface: DecimalUtilsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "uintToDecimalString(uint256)": TypedContractMethod<
    [value: BigNumberish],
    [string],
    "view"
  >;

  "uintToDecimalString(uint256,uint256)": TypedContractMethod<
    [value: BigNumberish, decimal: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "uintToDecimalString(uint256)"
  ): TypedContractMethod<[value: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "uintToDecimalString(uint256,uint256)"
  ): TypedContractMethod<
    [value: BigNumberish, decimal: BigNumberish],
    [string],
    "view"
  >;

  filters: {};
}
