/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface StringUtilsInterface extends Interface {
  getFunction(nameOrSignature: "hexToBytes" | "hexToBytes32"): FunctionFragment;

  encodeFunctionData(functionFragment: "hexToBytes", values: [string]): string;
  encodeFunctionData(
    functionFragment: "hexToBytes32",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "hexToBytes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hexToBytes32",
    data: BytesLike
  ): Result;
}

export interface StringUtils extends BaseContract {
  connect(runner?: ContractRunner | null): StringUtils;
  waitForDeployment(): Promise<this>;

  interface: StringUtilsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hexToBytes: TypedContractMethod<[hexStr: string], [string], "view">;

  hexToBytes32: TypedContractMethod<[hexStr: string], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hexToBytes"
  ): TypedContractMethod<[hexStr: string], [string], "view">;
  getFunction(
    nameOrSignature: "hexToBytes32"
  ): TypedContractMethod<[hexStr: string], [string], "view">;

  filters: {};
}
