/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
import type * as emailTxBuilderContracts from "./email-tx-builder-contracts";
export type { emailTxBuilderContracts };
